-- =============================================================================
-- Generated by lightline to lualine theme converter
--   https://gist.github.com/shadmansaleh/000871c9a608a012721c6acc6d7a19b9
-- License: MIT License
-- =============================================================================

local colors = {
  color1   = "#57c7ff",
  color2   = "#858db5",
  color3   = "#f1f1f0",
  color4   = "#44485b",
  color5   = "#5af78e",
  color8   = "#ff6ac1",
  color17  = "#626784",
  color11  = "#fad07a",
  color14  = "#ff5c57",
  color0   = "#3a3d4d",
}

local snazzy = {
  normal = {
    a = { fg = colors.color0, bg = colors.color1 , gui = "bold", },
    c = { fg = colors.color2, bg = colors.color0 },
    b = { fg = colors.color3, bg = colors.color4 },
  },
  insert = {
    a = { fg = colors.color0, bg = colors.color5 , gui = "bold", },
    b = { fg = colors.color3, bg = colors.color4 },
  },
  visual = {
    a = { fg = colors.color0, bg = colors.color8 , gui = "bold", },
    b = { fg = colors.color3, bg = colors.color4 },
  },
  command = {
    a = { fg = colors.color0, bg = colors.color11 , gui = "bold", },
    b = { fg = colors.color3, bg = colors.color4 },
  },
  replace = {
    a = { fg = colors.color0, bg = colors.color14 , gui = "bold", },
    b = { fg = colors.color3, bg = colors.color4 },
  },
  inactive = {
    a = { fg = colors.color2, bg = colors.color0 , gui = "bold", },
    c = { fg = colors.color17, bg = colors.color0 },
    b = { fg = colors.color17, bg = colors.color0 },
  },
}

return snazzy